[webserver]
port = ":8080"              # port to bind the web server to. defaults ":8080"
#ssl_cert = "fullchain.pem"  # ssl cert for serving by https
#ssl_key = "privkey.pem"     # ssl key for serving by https

  [webserver.headers]
  Access-Control-Allow-Origin = "*"
  Cache-Control = "no-cache, no-store, must-revalidate"

[observer]
type = "prometheus"         # configure the prometheus metric end point

[cache]                     # configure a tile cache
type = "file"               # a file cache will cache to the local file system
basepath = "/tmp/tegola"    # where to write the file cache

# register data providers
[[providers]]
name = "osm"                # provider name is referenced from map layers (required)
type = "postgis"            # the type of data provider. currently only supports postgis (required)
host = "postgis"            # postgis database host (required)
port = 5432                 # postgis database port (required)
database = "tegola"         # postgis database name (required)
user = "tegola"             # postgis database user (required)
password = "secret"         # postgis database password (required)
srid = 3857                 # The default srid for this provider. Defaults to WebMercator (3857) (optional)
max_connections = 50        # The max connections to maintain in the connection pool. Default is 100. (optional)
ssl_mode = "prefer"         # PostgreSQL SSL mode*. Default is "disable". (optional)

    # https://github.com/go-spatial/tegola-osm/blob/master/tegola.toml
    [[providers.layers]]
	name = "land_8-20"
	geometry_fieldname = "geometry"
	id_fieldname = "ogc_fid"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid FROM land_polygons WHERE wkb_geometry && !BBOX!"

	# Water
	[[providers.layers]]
	name = "water_areas"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type, area FROM osm_water_areas WHERE type IN ('water', 'pond', 'basin', 'canal', 'mill_pond', 'riverbank', 'dock') AND geometry && !BBOX!"

	[[providers.layers]]
	name = "water_areas_gen0"
	geometry_fieldname = "geometry"
	id_fieldname = "osm_id"
	sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, type, area FROM osm_water_areas_gen0 WHERE type IN ('water', 'pond', 'basin', 'canal', 'mill_pond', 'riverbank') AND area > 1000000000 AND geometry && !BBOX!"


# maps are made up of layers
[[maps]]
name = "osm"                               # used in the URL to reference this map (/maps/zoning)

    [[maps.layers]]
	name = "land"
	provider_layer = "osm.land_8-20"
	dont_simplify = true
	min_zoom = 8
	max_zoom = 20

	[[maps.layers]]
	name = "admin_lines"
	provider_layer = "osm.admin_boundaries_8-12"
	min_zoom = 8
	max_zoom = 12

    # ...
